### ISSUE TITLE
Unable to launch/start kawaii-player

### ISSUE THREAD

**Issue by All-io-X-oi-llA** [kanishka-linux/kawaii-player#26]
I installed kawaii-player via GDebi (kawaii-player-4.2.0-1.deb)
OS: ParrotSec v4.9
mpv & libmpv version: mpv (0.32.0-1) unstable
python-mpv version: python-mpv (0.4.6-1) unstable

Additionally installs:
`freeglut3 libboost-python1.67.0 libmpv-dev libqt5opengl5 python-pip-whl python3-dbus.mainloop.pyqt5 python3-libtorrent python3-opengl python3-pip python3-pyqt5.qtopengl python3-pyqt5.qtwebkit python3-taglib python3-wheel`

this is the output when i try execute kawaii-player in the terminal:
```
taglib --tagging-module--
DEBUG:OpenGL.platform.ctypesloader:Loaded libGL.so => libGL.so.1 <CDLL 'libGL.so.1', handle 2d9b890 at 0x7f2ee8912ee0>
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
posix mate
1280 800
800 1280
not enough values to unpack (expected 2, got 1) wrong values in config file
/usr/share/kawaii-player/kawaii_player.py:595: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.text.setMaximumHeight(self.height_allowed+50)
/usr/share/kawaii-player/kawaii_player.py:597: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.label.setMaximumHeight(self.height_allowed)
/usr/share/kawaii-player/kawaii_player.py:598: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.label.setMinimumHeight(self.height_allowed)
/usr/share/kawaii-player/kawaii_player.py:601: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.cover_label.setMaximumHeight(self.height_allowed+50)
/usr/share/kawaii-player/kawaii_player.py:602: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.cover_label.setMinimumHeight(self.height_allowed)
/usr/share/kawaii-player/kawaii_player.py:611: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.label_new.setMaximumHeight(2.5*self.height_allowed)
INFO::kawaii_player::update_video_dict_criteria: {'anime': 'Anime', 'movies': 'Movies', 'tv shows': 'TV Shows', 'cartoons': 'Cartoons', 'others': 'Others'}::['Anime', 'Movies', 'TV Shows', 'Cartoons', 'Others']::--1808--
INFO:__main__:{'anime': 'Anime', 'movies': 'Movies', 'tv shows': 'TV Shows', 'cartoons': 'Cartoons', 'others': 'Others'}::['Anime', 'Movies', 'TV Shows', 'Cartoons', 'Others']::--1808--
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
[1023, 28, 337, 226]
[454, 29, 910, 340] --music--mode--dimension--set--
best ----quality---
4 --site-index--
0 --addon-index--
Search --option--
0 --option-index--
  -------
0 --name-index--
0 --episode-index--
INFO::kawaii_player::main: [4, 0, 0, 0, 0]
INFO:__main__:[4, 0, 0, 0, 0]
INFO::kawaii_player::main: [0, 0, 0]
INFO:__main__:[0, 0, 0]
0 --video-aspect--
DEBUG::kawaii_player::main: fs=False
DEBUG:__main__:fs=False
DEBUG::kawaii_player::main: #BROWSER_BACKEND=QTWEBENGINE,QTWEBKIT
DEBUG:__main__:#BROWSER_BACKEND=QTWEBENGINE,QTWEBKIT
DEBUG::kawaii_player::main: #GET_LIBRARY=pycurl,curl,wget
DEBUG:__main__:#GET_LIBRARY=pycurl,curl,wget
DEBUG::kawaii_player::main: #IMAGE_FIT_OPTION=0-9
DEBUG:__main__:#IMAGE_FIT_OPTION=0-9
DEBUG::kawaii_player::main: #YTDL_PATH=default,automatic
DEBUG:__main__:#YTDL_PATH=default,automatic
INFO::kawaii_player::main: mpv_conf: False
INFO:__main__:mpv_conf: False
DEBUG::kawaii_player::main: #THEME=default,system,dark
DEBUG:__main__:#THEME=default,system,dark
DEBUG::kawaii_player::main: #EXTRA_PLAYERS=vlc,kodi etc..
DEBUG:__main__:#EXTRA_PLAYERS=vlc,kodi etc..
DEBUG::kawaii_player::main: #GLOBAL_FONT=Name of Font
DEBUG:__main__:#GLOBAL_FONT=Name of Font
DEBUG::kawaii_player::main: #THUMBNAIL_TEXT_COLOR/LIST_TEXT_COLOR=red,green,blue,yellow, gray,white,black,cyan,magenta,darkgray,lightgray,darkred, darkblue,darkyellow,transparent
DEBUG:__main__:#THUMBNAIL_TEXT_COLOR/LIST_TEXT_COLOR=red,green,blue,yellow, gray,white,black,cyan,magenta,darkgray,lightgray,darkred, darkblue,darkyellow,transparent
DEBUG::kawaii_player::main: #For Dark Theme, use lightgray, if white color looks bright
DEBUG:__main__:#For Dark Theme, use lightgray, if white color looks bright
DEBUG::kawaii_player::main: DejaVu Sans14
DEBUG:__main__:DejaVu Sans14
DEBUG::stylesheet::apply_stylesheet: min-height-box=height: 29px
DEBUG:__main__:min-height-box=height: 29px
DEBUG::stylesheet::apply_stylesheet: min-height-box=height: 29px
DEBUG:__main__:min-height-box=height: 29px
DEBUG::stylesheet::apply_stylesheet: min-height-box=height: 29px
DEBUG:__main__:min-height-box=height: 29px
0 0
plugins
<class 'str'> MyServer --addon-changed--
<class 'MyServer.MyServer'> MyServer --addon-changed--
MyServer select
MyServer
['Login', 'Logout', 'Discover', 'History', 'newversion']
MyServer 4 ==site_index
0 2
0 --dock-option---
65011718
Event Filter Installed in new_tray_widget
/usr/share/kawaii-player/kawaii_player.py:2029: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.text.setMaximumHeight(self.height_allowed+50)
/usr/share/kawaii-player/kawaii_player.py:2031: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.label.setMaximumHeight(self.height_allowed)
/usr/share/kawaii-player/kawaii_player.py:2032: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.label.setMinimumHeight(self.height_allowed)
/usr/share/kawaii-player/kawaii_player.py:2035: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.cover_label.setMaximumHeight(self.height_allowed+50)
/usr/share/kawaii-player/kawaii_player.py:2036: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.cover_label.setMinimumHeight(self.height_allowed)
/usr/share/kawaii-player/kawaii_player.py:2044: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.label_new.setMaximumHeight(2.5*self.height_allowed)
[0, 0]
not enough values to unpack (expected 2, got 1) wrong values in config file
Traceback (most recent call last):
  File "/usr/share/kawaii-player/kawaii_player.py", line 14944, in <module>
    main()
  File "/usr/share/kawaii-player/kawaii_player.py", line 14800, in main
    ui.setup_opengl_widget(app)
  File "/usr/share/kawaii-player/kawaii_player.py", line 13337, in setup_opengl_widget
    self.tab_5 = MpvOpenglWidget(MainWindow, self, logger, TMPDIR, libmpv_api, app)
  File "/usr/share/kawaii-player/mpv_opengl.py", line 349, in __init__
    self.init_opengl_render()
  File "/usr/share/kawaii-player/mpv_opengl.py", line 462, in init_opengl_render
    self.mpv = mpv.Context()
AttributeError: module 'mpv' has no attribute 'Context'
```

**Comment by All-io-X-oi-llA** [comment]
Finally got it working after installing
1.[PyOpenGL-accelerate](https://pypi.org/project/PyOpenGL-accelerate/)
2.[pympv](https://pypi.org/project/pympv/)
Problem Solved 😃
