### ISSUE TITLE
Message " restart player keep showing up

### ISSUE THREAD

**Issue by Moltkex** [kanishka-linux/kawaii-player#30]
First, great work! :+1:   I'm using Kawaii-player in Debian Testing with KDE, changed theme to system(Breeze) and now every time KP starts I get **restart player to apply settings** message even though theme's already being used. Is there any way to fix that?

**Comment by kanishka-linux** [comment]
Just looked into it. It seems like when either titlelist or playlist column is hidden at the time of closing application, one gets this message.

So for a time being, maybe you can unhide both titlelist and playlist column when closing kawaii-player, to get rid of the behaviour.

Thanks for reporting.

**Comment by Moltkex** [comment]
> Just looked into it. It seems like when either titlelist or playlist column is hidden at the time of closing application, one gets this message.
> 
> So for a time being, maybe you can unhide both titlelist and playlist column when closing kawaii-player, to get rid of the behaviour.
> 
> Thanks for reporting.

No problem. Will try that and report back. Thanks for the reply.

**Comment by Moltkex** [comment]
@kanishka-linux That didn't work, message keep showing up, I changed the theme back to default and it went away. Now, I have another problem: No sound. While trying your suggestion I found that there's no sound, I ran the app in konsole to see if I can see some kind of error message but saw nothing, maybe I'm missing something. This the output, maybe you could take a look and see something I didn't:
```bash
kawaii-player some_video.mkv
/usr/share/kawaii-player kawaii_player.py /home/moltke/Downloads/
['/usr/share/kawaii-player', '/usr/share/kawaii-player', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages']
--using pycurl--
QTWEBENGINE
Using QTWEBENGINE
/home/moltke/.config/kawaii-player/tmp posix
taglib --tagging-module--
DEBUG:OpenGL.platform.ctypesloader:Loaded libGL.so => libGL.so.1 <CDLL 'libGL.so.1', handle 3d3e360 at 0x7f349e0cfe50>
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
No module named 'mpv'
only opengl-cb api is available
libvlc not detected
posix plasma
1366 768
768 1366
not enough values to unpack (expected 2, got 1) wrong values in config file
INFO::kawaii_player::update_video_dict_criteria: {'anime': 'Anime', 'movies': 'Movies', 'tv shows': 'TV Shows', 'cartoons': 'Cartoons', 'others': 'Others'}::['Anime', 'Movies', 'TV Shows', 'Cartoons', 'Others']::--1808--
INFO:__main__:{'anime': 'Anime', 'movies': 'Movies', 'tv shows': 'TV Shows', 'cartoons': 'Cartoons', 'others': 'Others'}::['Anime', 'Movies', 'TV Shows', 'Cartoons', 'Others']::--1808--
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
QLayout: Attempting to add QLayout "" to ExtraToolBar "frame_extra_toolbar", which already has a layout
[1023, 28, 337, 226]
[454, 29, 910, 340] --music--mode--dimension--set--
best ----quality---
4 --site-index--
0 --addon-index--
Available --option--
0 --option-index--
  -------
0 --name-index--
0 --episode-index--
INFO::kawaii_player::main: [4, 0, 0, 0, 0]
INFO:__main__:[4, 0, 0, 0, 0]
INFO::kawaii_player::main: [0, 0, 0]
INFO:__main__:[0, 0, 0]
0 --video-aspect--
DEBUG::kawaii_player::main: fs=False
DEBUG:__main__:fs=False
DEBUG::kawaii_player::main: #BROWSER_BACKEND=QTWEBENGINE,QTWEBKIT
DEBUG:__main__:#BROWSER_BACKEND=QTWEBENGINE,QTWEBKIT
DEBUG::kawaii_player::main: #GET_LIBRARY=pycurl,curl,wget
DEBUG:__main__:#GET_LIBRARY=pycurl,curl,wget
DEBUG::kawaii_player::main: #IMAGE_FIT_OPTION=0-9
DEBUG:__main__:#IMAGE_FIT_OPTION=0-9
DEBUG::kawaii_player::main: #YTDL_PATH=default,automatic
DEBUG:__main__:#YTDL_PATH=default,automatic
INFO::kawaii_player::main: mpv_conf: False
INFO:__main__:mpv_conf: False
DEBUG::kawaii_player::main: #THEME=default,system,dark
DEBUG:__main__:#THEME=default,system,dark
DEBUG::kawaii_player::main: #EXTRA_PLAYERS=vlc,kodi etc..
DEBUG:__main__:#EXTRA_PLAYERS=vlc,kodi etc..
DEBUG::kawaii_player::main: #GLOBAL_FONT=Name of Font
DEBUG:__main__:#GLOBAL_FONT=Name of Font
DEBUG::kawaii_player::main: #THUMBNAIL_TEXT_COLOR/LIST_TEXT_COLOR=red,green,blue,yellow, gray,white,black,cyan,magenta,darkgray,lightgray,darkred, darkblue,darkyellow,transparent
DEBUG:__main__:#THUMBNAIL_TEXT_COLOR/LIST_TEXT_COLOR=red,green,blue,yellow, gray,white,black,cyan,magenta,darkgray,lightgray,darkred, darkblue,darkyellow,transparent
DEBUG::kawaii_player::main: #For Dark Theme, use lightgray, if white color looks bright
DEBUG:__main__:#For Dark Theme, use lightgray, if white color looks bright
DEBUG::kawaii_player::main: Bitstream Vera Sans12
DEBUG:__main__:Bitstream Vera Sans12
0 0
plugins
<class 'str'> MyServer --addon-changed--
<class 'MyServer.MyServer'> MyServer --addon-changed--
MyServer select
MyServer
['Login', 'Logout', 'Discover', 'History', 'newversion']
MyServer 4 ==site_index
0 2
0 --dock-option---
94371852
Could not parse stylesheet of object QLineProgress(0x4d5e710)
Event Filter Installed in new_tray_widget
[0, 0]
False update_playlist_thumb
Could not parse stylesheet of object QLineProgress(0x4d5e710)
00:41:48
2508 --mpvlength AV: 00:00:00 / 00:41:48 (0%) A-V:  0.282 Dropped: 2
Show/Hide Playlist
True update_playlist_thumb
Show/Hide Title List
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
25
0
0
Could not parse stylesheet of object QLineProgress(0x4d5e710)
QCssParser::parseColorValue: Specified color with alpha value but no alpha given: 'rgba 54,60,74'
QCssParser::parseColorValue: Specified color with alpha value but no alpha given: 'rgba 54,60,74'
25
25
25
25
some_video.mkv     /home/moltke/Downloads/some_video.mkv NONE
/home/moltke/.config/kawaii-player/thumbnails/PlayLists/TMP_PLAYLIST/some_video.mkv.jpg --img--place
303 --max--width--label--
00:41:48
2508 --mpvlength AV: 00:00:00 / 00:41:48 (0%) A-V:  0.005 Dropped: 1
^CTraceback (most recent call last):
  File "/usr/share/kawaii-player/kawaii_player.py", line 15465, in <module>
    main()
  File "/usr/share/kawaii-player/kawaii_player.py", line 15445, in main
    ret = app.exec_()
KeyboardInterrupt
```
By the way, sorry if it isn't right that I posted here instead of opening a new issue, but since I was already replying, thought it might be ok to do so, my apologies if it's not.

**Comment by kanishka-linux** [comment]
> That didn't work, message kept showing, 

that's strange, I reproduced the bug on osx, maybe I'll have to check on linux box. And to be honest, I hardly test system theme. Since they are hard to manage for different OS (gnu/linux, mac, windows). Every now and then some unexpected bug crops up in system themes, but I end up neglecting them :)

> While trying your suggestion I found that there's no sound,

maybe try toggling `A/V` button, or could be issue in setting audio driver.

see the available audio o/p driver `mpv -vo help`

and see `ao` value is set correctly in `Preferences/config`, it could be either `alsa` or `pulse`
after that check `use this config file` box. 

things should work.

> instead of opening a new issue,

that's fine, no problem

> Default theme is nicer

Glad you liked it. To be honest, it used to be my favourite and used to be default earlier. But in order to look good, it requires, high quality background images, which are generated from video source. If video source is of low quality, then overall it doesn't look good. Alternatively, one can grab background images from external source. As it was much more involved process, I decided to introduce dark theme, which doesn't require much fiddling. 

By the way this Default theme, looks very nice on large screens. Just connect your laptop to HDTV and control KP from web remote control. I've made lot of changes to remote control and added too many options. Only thing is web interface is pretty dry looking, but it does get its work done.

**Comment by Moltkex** [comment]
@kanishka-linux  Thanks for the quick reply and the help. Well, all it's good. Turns out somehow don't know why or how MPV was silenced in kmix/pulseaudio Plasma panel applet, I realized that because KP icon showed a "silenced volume icon(the volume with a cross or something)", so I open the mixer, enable sound, and now it's working again. Sorry for the trouble. 

>Glad you liked it. To be honest, it used to be my favourite and used to be default earlier. But in order to look good, it requires, high quality background images, which are generated from video source. If video source is of low quality, then overall it doesn't look good. Alternatively, one can grab background images from external source. As it was much more involved process, I decided to introduce dark theme, which doesn't require much fiddling.

Yeah, I do. I don't quite like dark themes that much to be honest, but this one looks pretty cool. Really nice work there. :+1: Sorry to keep bothering but, is there a way to change language settings? Do you need some help with translations? I can help with Spanish, just no coding but text strings only, like settings and stuff like that. Keep the great work! :grin:

**Comment by kanishka-linux** [comment]
> I don't quite like dark themes

yeah.. I'm also not big fan of it. Dark theme has ways to change color of background/control frame, and some default sub themes are provided for it. So normally I end up using some other lighter sub-theme within dark theme.

> is there a way to change language settings?

sorry, at the moment, there is no support for other languages. Most of the english words/sentences are hardcoded directly in the code.

> Do you need some help with translations? I can help with Spanish, just no coding but text strings only 

that will be great. I'll certainly try to look into how to provide proper translation support, so that people can contribute easily.
I don't know, when I'll be able to pick up changes though :)

You can open new issue for translation, will be easier to track it separately.

**Comment by Moltkex** [comment]
> You can open new issue for translation, will be easier to track it separately.

Done. :grin: 

> Dark theme has ways to change color of background/control frame, and some default sub themes are provided for it. So normally I end up using some other lighter sub-theme within dark theme.

Yeah, they do. I use a mix of both; a dark theme for some parts, like window decoration, and sidebars like in the file manager and a light theme for the rest.
