### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by Jack-Holborn** [kanishka-linux/kawaii-player#44]
Hello,

I'm trying to install player in Gentoo. I got all first steps running ok but pip install 'pkg_available_in_directory' (with package being kawaii-player-5.1.0.tar.gz) throws an error against missing mpv.c . here's the output of pip install command (as user) :
```
Processing ./kawaii-player-5.1.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pympv@ git+https://github.com/marcan/pympv.git (from kawaii-player==5.1.0)
  Cloning https://github.com/marcan/pympv.git to /tmp/pip-install-qksqkgq_/pympv_e37c3fe2e2f24bf28b38af4de2bd4a76
  Running command git clone --filter=blob:none --quiet https://github.com/marcan/pympv.git /tmp/pip-install-qksqkgq_/pympv_e37c3fe2e2f24bf28b38af4de2bd4a76
  Resolved https://github.com/marcan/pympv.git to commit a971cf477348f1188b0433b250a0aa513eb4db08
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyQt5 (from kawaii-player==5.1.0)
  Using cached PyQt5-5.15.9-cp37-abi3-manylinux_2_17_x86_64.whl (8.4 MB)
Collecting pycurl (from kawaii-player==5.1.0)
  Using cached pycurl-7.45.2-cp311-cp311-linux_x86_64.whl
Collecting bs4 (from kawaii-player==5.1.0)
  Using cached bs4-0.0.1-py3-none-any.whl
Collecting Pillow (from kawaii-player==5.1.0)
  Obtaining dependency information for Pillow from https://files.pythonhosted.org/packages/16/89/818fa238e37a47a29bb8495ca2cafdd514599a89f19ada7916348a74b5f9/Pillow-10.0.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata
  Using cached Pillow-10.0.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting mutagen (from kawaii-player==5.1.0)
  Using cached mutagen-1.46.0-py3-none-any.whl (193 kB)
Collecting lxml (from kawaii-player==5.1.0)
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/ed/62/ffc30348ae141f69f9f23b65ba769db7ca209856c9a9b3406279e0ea24de/lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl.metadata
  Using cached lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting youtube-dl (from kawaii-player==5.1.0)
  Using cached youtube_dl-2021.12.17-py2.py3-none-any.whl (1.9 MB)
Collecting certifi (from kawaii-player==5.1.0)
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting PyQtWebEngine (from kawaii-player==5.1.0)
  Using cached PyQtWebEngine-5.15.6-cp37-abi3-manylinux1_x86_64.whl (230 kB)
Collecting PyOpenGL (from kawaii-player==5.1.0)
  Obtaining dependency information for PyOpenGL from https://files.pythonhosted.org/packages/99/48/00e31747821d3fc56faddd00a4725454d1e694a8b67d715cf20f531506a5/PyOpenGL-3.1.7-py3-none-any.whl.metadata
  Using cached PyOpenGL-3.1.7-py3-none-any.whl.metadata (3.2 kB)
Collecting beautifulsoup4 (from bs4->kawaii-player==5.1.0)
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting PyQt5-sip<13,>=12.11 (from PyQt5->kawaii-player==5.1.0)
  Using cached PyQt5_sip-12.12.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.whl (371 kB)
Collecting PyQt5-Qt5>=5.15.2 (from PyQt5->kawaii-player==5.1.0)
  Using cached PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (59.9 MB)
Collecting PyQtWebEngine-Qt5>=5.15.0 (from PyQtWebEngine->kawaii-player==5.1.0)
  Using cached PyQtWebEngine_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (67.5 MB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4->kawaii-player==5.1.0)
  Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
Using cached lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl (7.9 MB)
Using cached Pillow-10.0.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)
Using cached PyOpenGL-3.1.7-py3-none-any.whl (2.4 MB)
Building wheels for collected packages: kawaii-player, pympv
  Building wheel for kawaii-player (pyproject.toml) ... done
  Created wheel for kawaii-player: filename=kawaii_player-5.1.0-py3-none-any.whl size=907228 sha256=b328cc7e9cc016bc592458e7ca8830457ad45539bcde20d2ab0d3f9cf53e8fc9
  Stored in directory: /home/jack/.cache/pip/wheels/93/c5/10/388c28206f1cd1b961afcfa8208123a340166887cf094d9de4
  Building wheel for pympv (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pympv (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'mpv' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      x86_64-pc-linux-gnu-gcc -Wsign-compare -DNDEBUG -fPIC -I/var/src/kawaii-player/pyenv/include -I/usr/include/python3.11 -c mpv.c -o build/temp.linux-x86_64-cpython-311/mpv.o
      cc1: erreur fatale: mpv.c : Aucun fichier ou dossier de ce type
      compilation terminée.
      error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pympv
Successfully built kawaii-player
Failed to build pympv
ERROR: Could not build wheels for pympv, which is required to install pyproject.toml-based projects
```
mpv is installed via my package manager, I don't understant why it needs mpv.c file. Do I need to get it from sources?
What am I missing?
Thanks for your kind help.

**Comment by kanishka-linux** [comment]
pympv has `mpv.pyx` and from that `mpv.c` is created using `cython`. Maybe cython is not able to find `mpv.pyx` file path.

Can you try installing pympv manually first, and see if it is installable?

```
$ git clone https://github.com/marcan/pympv.git
$ cd pympv
$ python3 setup.py sdist
$ pip3 install dist/pympv-0.8.0.tar.gz
```
If it installs properly then you can remove the pympv dependency from kawaii-player setup.py and see if that works.

**Comment by Jack-Holborn** [comment]
same error :

```
Processing ./dist/pympv-0.8.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pympv
  Building wheel for pympv (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pympv (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'mpv' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      x86_64-pc-linux-gnu-gcc -Wsign-compare -DNDEBUG -fPIC -I/var/src/kawaii-player/pyenv/include -I/usr/include/python3.11 -c mpv.c -o build/temp.linux-x86_64-cpython-311/mpv.o
      cc1: fatal error: mpv.c: No such file or directory
      compilation terminated.
      error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pympv
Failed to build pympv
ERROR: Could not build wheels for pympv, which is required to install pyproject.toml-based projects
```

it seems like mpv.c is not created. I don't know python so I don't know what to look for, sry for that. Readme says I don't have to install python dependencies from package manager, right?

**Comment by Jack-Holborn** [comment]
No attachment, so I put this here in case it is useful

```
{
  "version": "1",
  "pip_version": "23.2",
  "installed": [
    {
      "metadata": {
        "metadata_version": "2.1",
        "name": "setuptools",
        "version": "67.8.0",
        "summary": "Easily download, build, install, upgrade, and uninstall Python packages",
        "description": ".. image:: https://img.shields.io/pypi/v/setuptools.svg\n   :target: https://pypi.org/project/setuptools\n\n.. image:: https://img.shields.io/pypi/pyversions/setuptools.svg\n\n.. image:: https://github.com/pypa/setuptools/workflows/tests/badge.svg\n   :target: https://github.com/pypa/setuptools/actions?query=workflow%3A%22tests%22\n   :alt: tests\n\n.. image:: https://img.shields.io/badge/code%20style-black-000000.svg\n   :target: https://github.com/psf/black\n   :alt: Code style: Black\n\n.. image:: https://img.shields.io/readthedocs/setuptools/latest.svg\n    :target: https://setuptools.pypa.io\n\n.. image:: https://img.shields.io/badge/skeleton-2023-informational\n   :target: https://blog.jaraco.com/skeleton\n\n.. image:: https://img.shields.io/codecov/c/github/pypa/setuptools/master.svg?logo=codecov&logoColor=white\n   :target: https://codecov.io/gh/pypa/setuptools\n\n.. image:: https://tidelift.com/badges/github/pypa/setuptools?style=flat\n   :target: https://tidelift.com/subscription/pkg/pypi-setuptools?utm_source=pypi-setuptools&utm_medium=readme\n\n.. image:: https://img.shields.io/discord/803025117553754132\n   :target: https://discord.com/channels/803025117553754132/815945031150993468\n   :alt: Discord\n\nSee the `Installation Instructions\n<https://packaging.python.org/installing/>`_ in the Python Packaging\nUser's Guide for instructions on installing, upgrading, and uninstalling\nSetuptools.\n\nQuestions and comments should be directed to `GitHub Discussions\n<https://github.com/pypa/setuptools/discussions>`_.\nBug reports and especially tested patches may be\nsubmitted directly to the `bug tracker\n<https://github.com/pypa/setuptools/issues>`_.\n\n\nCode of Conduct\n===============\n\nEveryone interacting in the setuptools project's codebases, issue trackers,\nchat rooms, and fora is expected to follow the\n`PSF Code of Conduct <https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md>`_.\n\n\nFor Enterprise\n==============\n\nAvailable as part of the Tidelift Subscription.\n\nSetuptools and the maintainers of thousands of other packages are working with Tidelift to deliver one enterprise subscription that covers all of the open source you use.\n\n`Learn more <https://tidelift.com/subscription/pkg/pypi-setuptools?utm_source=pypi-setuptools&utm_medium=referral&utm_campaign=github>`_.\n\n\nSecurity Contact\n================\n\nTo report a security vulnerability, please use the\n`Tidelift security contact <https://tidelift.com/security>`_.\nTidelift will coordinate the fix and disclosure.\n",
        "keywords": [
          "CPAN",
          "PyPI",
          "distutils",
          "eggs",
          "package",
          "management"
        ],
        "home_page": "https://github.com/pypa/setuptools",
        "author": "Python Packaging Authority",
        "author_email": "distutils-sig@python.org",
        "classifier": [
          "Development Status :: 5 - Production/Stable",
          "Intended Audience :: Developers",
          "License :: OSI Approved :: MIT License",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3 :: Only",
          "Topic :: Software Development :: Libraries :: Python Modules",
          "Topic :: System :: Archiving :: Packaging",
          "Topic :: System :: Systems Administration",
          "Topic :: Utilities"
        ],
        "requires_dist": [
          "sphinx (>=3.5) ; extra == 'docs'",
          "jaraco.packaging (>=9) ; extra == 'docs'",
          "rst.linker (>=1.9) ; extra == 'docs'",
          "furo ; extra == 'docs'",
          "sphinx-lint ; extra == 'docs'",
          "jaraco.tidelift (>=1.4) ; extra == 'docs'",
          "pygments-github-lexers (==0.0.5) ; extra == 'docs'",
          "sphinx-favicon ; extra == 'docs'",
          "sphinx-inline-tabs ; extra == 'docs'",
          "sphinx-reredirects ; extra == 'docs'",
          "sphinxcontrib-towncrier ; extra == 'docs'",
          "sphinx-notfound-page (==0.8.3) ; extra == 'docs'",
          "sphinx-hoverxref (<2) ; extra == 'docs'",
          "pytest (>=6) ; extra == 'testing'",
          "pytest-checkdocs (>=2.4) ; extra == 'testing'",
          "pytest-enabler (>=1.3) ; extra == 'testing'",
          "flake8-2020 ; extra == 'testing'",
          "virtualenv (>=13.0.0) ; extra == 'testing'",
          "wheel ; extra == 'testing'",
          "pip (>=19.1) ; extra == 'testing'",
          "jaraco.envs (>=2.2) ; extra == 'testing'",
          "pytest-xdist ; extra == 'testing'",
          "jaraco.path (>=3.2.0) ; extra == 'testing'",
          "build[virtualenv] ; extra == 'testing'",
          "filelock (>=3.4.0) ; extra == 'testing'",
          "pip-run (>=8.8) ; extra == 'testing'",
          "ini2toml[lite] (>=0.9) ; extra == 'testing'",
          "tomli-w (>=1.0.0) ; extra == 'testing'",
          "pytest-timeout ; extra == 'testing'",
          "pytest-perf ; extra == 'testing'",
          "pytest ; extra == 'testing-integration'",
          "pytest-xdist ; extra == 'testing-integration'",
          "pytest-enabler ; extra == 'testing-integration'",
          "virtualenv (>=13.0.0) ; extra == 'testing-integration'",
          "tomli ; extra == 'testing-integration'",
          "wheel ; extra == 'testing-integration'",
          "jaraco.path (>=3.2.0) ; extra == 'testing-integration'",
          "jaraco.envs (>=2.2) ; extra == 'testing-integration'",
          "build[virtualenv] ; extra == 'testing-integration'",
          "filelock (>=3.4.0) ; extra == 'testing-integration'",
          "pytest-black (>=0.3.7) ; (platform_python_implementation != \"PyPy\") and extra == 'testing'",
          "pytest-cov ; (platform_python_implementation != \"PyPy\") and extra == 'testing'",
          "pytest-mypy (>=0.9.1) ; (platform_python_implementation != \"PyPy\") and extra == 'testing'",
          "pytest-ruff ; (sys_platform != \"cygwin\") and extra == 'testing'"
        ],
        "requires_python": ">=3.7",
        "project_url": [
          "Documentation, https://setuptools.pypa.io/",
          "Changelog, https://setuptools.pypa.io/en/stable/history.html"
        ],
        "provides_extra": [
          "certs",
          "docs",
          "ssl",
          "testing",
          "testing-integration"
        ]
      },
      "metadata_location": "/var/src/kawaii-player/pyenv/lib/python3.11/site-packages/setuptools-67.8.0.dist-info",
      "installer": "pip",
      "requested": true
    },
    {
      "metadata": {
        "metadata_version": "2.1",
        "name": "pip",
        "version": "23.2",
        "summary": "The PyPA recommended tool for installing Python packages.",
        "description": "pip - The Python Package Installer\n==================================\n\n.. image:: https://img.shields.io/pypi/v/pip.svg\n   :target: https://pypi.org/project/pip/\n\n.. image:: https://readthedocs.org/projects/pip/badge/?version=latest\n   :target: https://pip.pypa.io/en/latest\n\npip is the `package installer`_ for Python. You can use pip to install packages from the `Python Package Index`_ and other indexes.\n\nPlease take a look at our documentation for how to install and use pip:\n\n* `Installation`_\n* `Usage`_\n\nWe release updates regularly, with a new version every 3 months. Find more details in our documentation:\n\n* `Release notes`_\n* `Release process`_\n\nIn pip 20.3, we've `made a big improvement to the heart of pip`_; `learn more`_. We want your input, so `sign up for our user experience research studies`_ to help us do it right.\n\n**Note**: pip 21.0, in January 2021, removed Python 2 support, per pip's `Python 2 support policy`_. Please migrate to Python 3.\n\nIf you find bugs, need help, or want to talk to the developers, please use our mailing lists or chat rooms:\n\n* `Issue tracking`_\n* `Discourse channel`_\n* `User IRC`_\n\nIf you want to get involved head over to GitHub to get the source code, look at our development documentation and feel free to jump on the developer mailing lists and chat rooms:\n\n* `GitHub page`_\n* `Development documentation`_\n* `Development IRC`_\n\nCode of Conduct\n---------------\n\nEveryone interacting in the pip project's codebases, issue trackers, chat\nrooms, and mailing lists is expected to follow the `PSF Code of Conduct`_.\n\n.. _package installer: https://packaging.python.org/guides/tool-recommendations/\n.. _Python Package Index: https://pypi.org\n.. _Installation: https://pip.pypa.io/en/stable/installation/\n.. _Usage: https://pip.pypa.io/en/stable/\n.. _Release notes: https://pip.pypa.io/en/stable/news.html\n.. _Release process: https://pip.pypa.io/en/latest/development/release-process/\n.. _GitHub page: https://github.com/pypa/pip\n.. _Development documentation: https://pip.pypa.io/en/latest/development\n.. _made a big improvement to the heart of pip: https://pyfound.blogspot.com/2020/11/pip-20-3-new-resolver.html\n.. _learn more: https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020\n.. _sign up for our user experience research studies: https://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html\n.. _Python 2 support policy: https://pip.pypa.io/en/latest/development/release-process/#python-2-support\n.. _Issue tracking: https://github.com/pypa/pip/issues\n.. _Discourse channel: https://discuss.python.org/c/packaging\n.. _User IRC: https://kiwiirc.com/nextclient/#ircs://irc.libera.chat:+6697/pypa\n.. _Development IRC: https://kiwiirc.com/nextclient/#ircs://irc.libera.chat:+6697/pypa-dev\n.. _PSF Code of Conduct: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md\n",
        "home_page": "https://pip.pypa.io/",
        "author": "The pip developers",
        "author_email": "distutils-sig@python.org",
        "license": "MIT",
        "classifier": [
          "Development Status :: 5 - Production/Stable",
          "Intended Audience :: Developers",
          "License :: OSI Approved :: MIT License",
          "Topic :: Software Development :: Build Tools",
          "Programming Language :: Python",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3 :: Only",
          "Programming Language :: Python :: 3.7",
          "Programming Language :: Python :: 3.8",
          "Programming Language :: Python :: 3.9",
          "Programming Language :: Python :: 3.10",
          "Programming Language :: Python :: 3.11",
          "Programming Language :: Python :: 3.12",
          "Programming Language :: Python :: Implementation :: CPython",
          "Programming Language :: Python :: Implementation :: PyPy"
        ],
        "requires_python": ">=3.7",
        "project_url": [
          "Documentation, https://pip.pypa.io",
          "Source, https://github.com/pypa/pip",
          "Changelog, https://pip.pypa.io/en/stable/news/"
        ]
      },
      "metadata_location": "/var/src/kawaii-player/pyenv/lib/python3.11/site-packages/pip-23.2.dist-info",
      "installer": "pip",
      "requested": true
    }
  ],
  "environment": {
    "implementation_name": "cpython",
    "implementation_version": "3.11.4",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_release": "6.1.28-gentoo_winbox-i7",
    "platform_system": "Linux",
    "platform_version": "#1 SMP PREEMPT_DYNAMIC Sun May 28 18:44:08 CEST 2023",
    "python_full_version": "3.11.4",
    "platform_python_implementation": "CPython",
    "python_version": "3.11",
    "sys_platform": "linux"
  }
}
```

**Comment by Jack-Holborn** [comment]
I manage to get a lot more verbose output, to no avail, I'm afraid so : 

```
$>LC_ALL=C pip3 -vvv install dist/pympv-0.8.0.tar.gz 
Using pip 23.2 from /var/src/kawaii-player/pyenv/lib/python3.11/site-packages/pip (python 3.11)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-build-tracker-uriktot0
Initialized build tracking at /tmp/pip-build-tracker-uriktot0
Created build tracker: /tmp/pip-build-tracker-uriktot0
Entered build tracker: /tmp/pip-build-tracker-uriktot0
Created temporary directory: /tmp/pip-install-2a84uos6
Created temporary directory: /tmp/pip-ephem-wheel-cache-0363_nzi
Processing ./dist/pympv-0.8.0.tar.gz
  Created temporary directory: /tmp/pip-req-build-ymthkp_3
  Added file:///var/src/kawaii-player/pympv/dist/pympv-0.8.0.tar.gz to build tracker '/tmp/pip-build-tracker-uriktot0'
  Created temporary directory: /tmp/pip-build-env-0bz2fajp
  Running command pip subprocess to install build dependencies
  Using pip 23.2 from /var/src/kawaii-player/pyenv/lib/python3.11/site-packages/pip (python 3.11)
  Collecting setuptools>=40.8.0
    Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/c7/42/be1c7bbdd83e1bfb160c94b9cafd8e25efc7400346cf7ccdbdb452c467fa/setuptools-68.0.0-py3-none-any.whl.metadata
    Using cached setuptools-68.0.0-py3-none-any.whl.metadata (6.4 kB)
  Collecting wheel
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
  Installing collected packages: wheel, setuptools
    Creating /tmp/pip-build-env-0bz2fajp/overlay/bin
    changing mode of /tmp/pip-build-env-0bz2fajp/overlay/bin/wheel to 755
  Successfully installed setuptools-68.0.0 wheel-0.40.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  writing pympv.egg-info/PKG-INFO
  writing dependency_links to pympv.egg-info/dependency_links.txt
  writing top-level names to pympv.egg-info/top_level.txt
  reading manifest file 'pympv.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'pympv.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Created temporary directory: /tmp/pip-modern-metadata-6av2u3py
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-6av2u3py/pympv.egg-info
  writing /tmp/pip-modern-metadata-6av2u3py/pympv.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-6av2u3py/pympv.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-modern-metadata-6av2u3py/pympv.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-6av2u3py/pympv.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-6av2u3py/pympv.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-6av2u3py/pympv.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-6av2u3py/pympv-0.8.0.dist-info'
  Preparing metadata (pyproject.toml) ... done
  Source in /tmp/pip-req-build-ymthkp_3 has version 0.8.0, which satisfies requirement pympv==0.8.0 from file:///var/src/kawaii-player/pympv/dist/pympv-0.8.0.tar.gz
  Removed pympv==0.8.0 from file:///var/src/kawaii-player/pympv/dist/pympv-0.8.0.tar.gz from build tracker '/tmp/pip-build-tracker-uriktot0'
Created temporary directory: /tmp/pip-unpack-kpdqyje6
Building wheels for collected packages: pympv
  Created temporary directory: /tmp/pip-wheel-11ghrr0m
  Destination directory: /tmp/pip-wheel-11ghrr0m
  Running command Building wheel for pympv (pyproject.toml)
  running bdist_wheel
  running build
  running build_ext
  building 'mpv' extension
  creating build
  creating build/temp.linux-x86_64-cpython-311
  x86_64-pc-linux-gnu-gcc -Wsign-compare -DNDEBUG -fPIC -I/var/src/kawaii-player/pyenv/include -I/usr/include/python3.11 -c mpv.c -o build/temp.linux-x86_64-cpython-311/mpv.o
  cc1: fatal error: mpv.c: No such file or directory
  compilation terminated.
  error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for pympv (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /var/src/kawaii-player/pyenv/bin/python /var/src/kawaii-player/pyenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp0ru_7jd2
  cwd: /tmp/pip-req-build-ymthkp_3
  Building wheel for pympv (pyproject.toml) ... error
  ERROR: Failed building wheel for pympv
Failed to build pympv
ERROR: Could not build wheels for pympv, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/var/src/kawaii-player/pyenv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/var/src/kawaii-player/pyenv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/src/kawaii-player/pyenv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 429, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for pympv, which is required to install pyproject.toml-based projects
Remote version of pip: 23.2
Local version of pip:  23.2
Was pip installed by pip? True
Removed build tracker: '/tmp/pip-build-tracker-uriktot0'

```

**Comment by kanishka-linux** [comment]
I've added `mpv.c` [here](https://github.com/kanishka-linux/kawaii-player/tree/master/mpv) which is generated by cython.
Try copying the same `mpv.c` in the `pympv` cloned repo and then try to install pympv again. It is bruteforce approach though, and not recommended one :)

I'll try to find somewhat better way add this pympv dependency. Maybe I'll have to keep separate copy of pympv in the kawaii-player project itself, for better installation process. Will look into it in upcoming weeks.
