### ISSUE TITLE
Please Help, why dont work. i use arch linux

### ISSUE THREAD

**Issue by Foxxx98** [kanishka-linux/kawaii-player#47]
['/usr/lib/python3.11/site-packages/kawaii_player', '/usr/bin', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
--using default pycurl--
Traceback (most recent call last):
  File "/sbin/kawaii-player-console", line 33, in <module>
    sys.exit(load_entry_point('kawaii-player==5.0.0', 'console_scripts', 'kawaii-player-console')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sbin/kawaii-player-console", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/kawaii_player/kawaii_player.py", line 93, in <module>
    from guisignals import GUISignals
  File "/usr/lib/python3.11/site-packages/kawaii_player/guisignals.py", line 27, in <module>
    from settings_widget import LoginPCToPC
  File "/usr/lib/python3.11/site-packages/kawaii_player/settings_widget.py", line 32, in <module>
    from widgets.optionwidgets import QPushButtonExtra
  File "/usr/lib/python3.11/site-packages/kawaii_player/widgets/optionwidgets.py", line 16, in <module>
    from mpv_bak import MPV
  File "/usr/lib/python3.11/site-packages/kawaii_player/mpv_bak.py", line 409, in <module>
    _handle_func('mpv_detach_destroy',          [],                                         None, errcheck=None)
  File "/usr/lib/python3.11/site-packages/kawaii_player/mpv_bak.py", line 366, in _handle_func
    func = getattr(backend, name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /usr/lib/libmpv.so.2: undefined symbol: mpv_detach_destroy

**Comment by kanishka-linux** [comment]
you can check this [issue](https://github.com/kanishka-linux/kawaii-player/issues/42). 
Please try to build/install from master.
